project:
  type: book
  
title: "Micro-econometrics with R"
titlepage: true
titlepage-color: "FFF5EE"
titlepage-rule-height: 2
titlepage-logo: "./latex/cemoi.png"

book:
  author: "Yves Croissant"
  date: "17/11/2023"
  chapters:
  - index.qmd
  - part: OLS.qmd
    chapters:
      - ./chapters/simple_regression.qmd
  #     - ./chapters/simple_regression_properties.qmd
  #     - ./chapters/multiple_regression.qmd
  #     - ./chapters/coefficients.qmd
  # - part: beyond_OLS.qmd
  #   chapters:
  #     - ./chapters/maximum_likelihood.qmd
  #     - ./chapters/non_spherical.qmd
  #     - ./chapters/endogeneity.qmd
  #     - ./chapters/treateff.qmd
  #     - ./chapters/spatial.qmd
  # - part: special_responses.qmd
  #   chapters:
  #     - ./chapters/binomial.qmd
  #     - ./chapters/tobit.qmd
  #     - ./chapters/count.qmd
  #     - ./chapters/duration.qmd
  #     - ./chapters/rum.qmd
  - ./chapters/references.qmd
bibliography: references.bib

knitr:
  opts_chunk:
    message: false
    warning: false
    cache: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: krantz 
    classoption: [krantz2, a4paper]
#    classoption: [krantz2, a4paper, pdf]
#    documentclass: scrreprt
#    template: ./latex/eisvogel.tex
#    toc-own-page: true
#    include-in-header: ./latex/macros.tex
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

editor: source
