project:
  type: book
  
lot: true
lof: true

book:
  title: "Microeconometrics with R"
  author: "Yves Croissant"
  date: "2024/06/04"
  chapters:
  - index.qmd
  - part: OLS.qmd
    chapters:
      - chapters/simple_regression.qmd
      - chapters/simple_regression_properties.qmd
  - chapters/multiple_regression.qmd
  - chapters/coefficients.qmd
  - part: beyond_OLS.qmd
    chapters:
      - chapters/maximum_likelihood.qmd
      - chapters/non_spherical.qmd
      - chapters/endogeneity.qmd
      - chapters/treateff.qmd
      - chapters/spatial.qmd
  - part: special_responses.qmd
    chapters:
      - chapters/binomial.qmd
      - chapters/tobit.qmd
      - chapters/count.qmd
      - chapters/duration.qmd
      - chapters/rum.qmd
  - references.qmd
  
bibliography: references.bib

knitr:
  opts_chunk:
    message: false
    warning: false
    cache: false

format:
  html:
    number-depth: 2
    theme: cosmo
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68
  pdf:
    documentclass: krantz 
    classoption: [krantz2, a4paper]
    keep-tex: true
    include-in-header: 
      text: |
        \usepackage{makecell}
        \usepackage{makeidx}
        \usepackage{imakeidx}
        \usepackage{ifthen}
        \usepackage{setspace}
        \makeindex[name=general,title=General]
        \makeindex[name=author,title=Authors,columns=3]
        \makeindex[name=general,title=General index]
        \makeindex[name=data,title=Data Sets]
        \makeindex[name=functions,title=Functions]
        \makeindex[name=libraries,title=Libraries]
        \usepackage{pdflscape}
        \newcommand\bookepigraph[4]{
        \vspace{1em}\hfill{}\begin{minipage}{#1}{\begin{spacing}{0.9}
        \small\noindent\textit{#2}\end{spacing}
        \vspace{1em}
        \hfill{}{#3}\\
        \begin{flushright}{#4}\end{flushright}}
        \end{minipage}}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \newcommand{\idxfun}[2]{\index[functions]{#1@\texttt{#2::#1}}\index[libraries]{\textbf{#2}!\texttt{#1}}}
        \newcommand{\idxdata}[3][void]{\ifthenelse{\equal{#1}{void}}{\index[data]{#2@\texttt{#3::#2}}}{\index[data]{#2@\texttt{#3::#2}|#1}}}
        \indexsetup{level=\section*,toclevel=section,noclearpage}
        \pagenumbering{roman}
    include-before-body: 
      text: |
        \cleardoublepage
        \vspace{5cm}
        \bookepigraph{5cm}
        {The most important date in a man's life is that of his father's death.}
        {Georges Simenon}
        {Le Fils, 1957}
        \footnote{Cited by Pierre Assouline, Simenon : biographie, Paris : Julliard, 1992}
        \cleardoublepage
        \frontmatter
    include-after-body:
      text: |
        \cleardoublepage
        \backmatter
        \addcontentsline{toc}{chapter}{Indexes}
        \chapter*{Indexes}
        \printindex[general]
        \printindex[author]
        \printindex[data]
        \printindex[functions]
        \clearpage
        \printindex[libraries]

editor: source
